services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BASE_API_URL=http://localhost:5000/api
    environment:
      - BASE_API_URL=http://server:5000/api
      - NEXT_PUBLIC_BASE_API_URL=http://localhost:5000/api
    depends_on:
      - server
    ports:
      - "80:3000"
    networks:
      - app-network
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge