services:
  client:
    # image: ghcr.io/romankarbivskyi/market-masters-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BASE_API_URL=http://localhost:5000/api
    environment:
      - NEXT_PUBLIC_BASE_API_URL=http://localhost:5000/api
      - BASE_API_URL=http://server:5000/api
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network
  server:
    # image: ghcr.io/romankarbivskyi/market-masters-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - client
      - server
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  app-network:
    driver: bridge