services:
  client:
    # image: ghcr.io/romankarbivskyi/market-masters-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BASE_API_URL=https://mmasters.live/api
        - NEXT_PUBLIC_WEB3FORMS_KEY=web3forms_key
    environment:
      - NEXT_PUBLIC_BASE_API_URL=https://mmasters.live/api
      - BASE_API_URL=http://server:5000/api
    depends_on:
      - server
      - postgres
    networks:
      - app-network

  server:
    # image: ghcr.io/romankarbivskyi/market-masters-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - PORT=5000
    networks:
      - app-network
  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  pgdata: