services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    ports:
      - "80:3000"
    env_file:
      - ./client/.env
    networks:
      - app-network
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    networks:
      - app-network
networks:
  app-network:
    driver: bridge