services:
  client:
    image: ghcr.io/romankarbivskyi/market-masters-client:latest
    depends_on:
      - server
    ports:
      - "80:3000"
    networks:
      - app-network
  server:
    image: ghcr.io/romankarbivskyi/market-masters-server:latest
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge