services:
  client:
    image: ghcr.io/romankarbivskyi/market-masters-client:latest
    ports:
      - "80:3000"
    env_file:
      - ./client/.env
    networks:
      - app-network
  server:
    image: ghcr.io/romankarbivskyi/market-masters-server:latest
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    networks:
      - app-network
networks:
  app-network:
    driver: bridge