name: Deploy App

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push client image
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-client:latest
          build-args: |
            NEXT_PUBLIC_BASE_API_URL=https://www.mmasters.live/api
            NEXT_PUBLIC_WEB3FORMS_KEY=${{ secrets.WEB3FORMS_KEY }}

      - name: Build and push server image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-server:latest

      - name: Connect to VPS and deploy using SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
            cd /app
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-client:latest
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-server:latest
            docker-compose up -d --force-recreate
          EOF
